### ISSUE TITLE
../config/default.yaml error Ask Question

### ISSUE THREAD

**Issue by TenzinJinpa2019** [xing-hu/EMSE-DeepCom#10]
I am trying to train the model through the google cloud but I getting the same error : 

`File "__main__.py", line 329, in <module>
    main()
  File "__main__.py", line 126, in main
    with open('../config/default.yaml') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../config/default.yaml'
tjinpa2019@cloudshell:~/EMSE-DeepCom/source code (bamboo-truck-281120)$`

Could you kindly help me in this as I am stuck with the  problem for sometime now.

**Comment by xing-hu** [comment]
I think you can create directory "config" and put the file "default.yaml" into it. The default.yaml can be downloaded from this repo.
