### ISSUE TITLE
The file get_ast.py is confusing and imcomplete

### ISSUE THREAD

**Issue by Henrykwokkk** [xing-hu/EMSE-DeepCom#18]
@xing-hu 
In order to verify the function of the file get_ast.py, I input the train.token.code, which had 445,812 samples, to the get_ast.py. However, only 27,025 AST samples were generated after processing. It seemed that lots of code samples were filtered in try & except statement in the second function 'get_ast(file_name, w)', and the AST file was strange, too. An example is shown below.

`e.g. [{"id": 0, "type": "MethodDeclaration(annotations=[], body=[ReturnStatement(expression=MethodInvocation(arguments=[], member=size, postfix_operators=[], prefix_operators=[], qualifier=gralComponents, selectors=[], type_arguments=None), label=None)], documentation=None, modifiers={'public'}, name=numGeneratedSequences, parameters=[], return_type=BasicType(dimensions=[], name=int), throws=None, type_parameters=None)", "children": [1, 2], "value": "numGeneratedSequences"}, {"id": 1, "type": "BasicType(dimensions=[], name=int)", "value": "int"}, {"id": 2, "type": "ReturnStatement(expression=MethodInvocation(arguments=[], member=size, postfix_operators=[], prefix_operators=[], qualifier=gralComponents, selectors=[], type_arguments=None), label=None)", "children": [3], "value": "return"}, {"id": 3, "type": "MethodInvocation(arguments=[], member=size, postfix_operators=[], prefix_operators=[], qualifier=gralComponents, selectors=[], type_arguments=None)", "value": "gralComponents.size"}]`

  

On the other hand, when I input the train.source file and only executed the second function 'get_ast(file_name, w)', the code samples were not be filtered. All samples generated AST but the structure was still strange. I think both the first function 'process_source(file_name, save_file)' and the second function 'get_ast(file_name, w)' have some problems, or maybe train.token.code is not the input of the get_ast.py.

**Comment by TenzinJinpa2019** [comment]
Hi @guohanyang1994 ,

I have the same issue however you can fixed the issue by modifying the code "d["type"] = str(node)" so that you can only get the type not all of the string. 


Hope this will be helpful to you.

**Comment by Henrykwokkk** [comment]
Hi @TenzinJinpa2019 ,
Thanks for your reply. By the way, did you have some problems when inputting the train.token.code to the get_ast.py? Many samples are filtered when executing the second function get_ast. I think the raw data file has some problems. How to ensure the integrity of the sample when executing the function?

Thanks!

**Comment by TenzinJinpa2019** [comment]
hi @guohanyang1994  I think instead of "train.token.code" you should try with "train.source" and generate  AST file. You can crosscheck the validity by generating the SBT of the file and compare it the file provided by the author. 

Hope this will resolve your issue !

**Comment by 2017040264** [comment]
hi @guohanyang1994 Have you solved your problem ?

**Comment by TranSMS** [comment]
Hi @TenzinJinpa2019 ,
I also have the same question, I want to ask you how to only get the type. Which parts of the code need to be modified？

Thanks!
