### ISSUE TITLE
The link of the dataset has broken

### ISSUE THREAD

**Issue by GoneZ5** [xing-hu/EMSE-DeepCom#25]
作者您好！
readme中的数据集链接失效了，导致无法下载vocab.code文件，能麻烦您更新一下链接吗？十分感谢！

**Comment by Manas-Embold** [comment]
Dataset Link is broken @xing-hu 
Kindly share the link to dataset.
Thanks

**Comment by codekali** [comment]
Please update it as soon  as possible.

**Comment by xing-hu** [comment]
The link has updated
