### ISSUE TITLE
链接无效

### ISSUE THREAD

**Issue by s1530129650** [xing-hu/EMSE-DeepCom#26]
As the limitation of LFS, the dataset can be downloaded from Google Drive (dataset version 1)

这个链接失效啦.

Q1: 请问这个链接里data有paper中的提到的SBT数据吗？
Q2：现有的代码得到的SBT看起来只用到了type，而不是type_value 的形式。详见https://github.com/xing-hu/EMSE-DeepCom/blob/master/data_utils/ast_traversal.py#L9
Q3：我用你share出来的代码处理了数据，跑出来的bleu4只有10几，无限增大epoch至4000也just到20，离paper中deepcom的38，h-deepcom的39差的好多。

please feel free to reply me . Thanks 

Many Thanks 

Ensheng

**Comment by xing-hu** [comment]
Q1. 当前链接的谷歌账号被停用导致链接失效，目前正在申诉中。同时，我也在寻找数据，再重新上传。
Q2. type_value 为论文 Deep Code Comment Generation论文中的构造方法，在emse论文中，只使用了type
Q3. 在重新上传数据时，我会将生成结果也上传

**Comment by s1530129650** [comment]
谢谢

**Comment by s1530129650** [comment]
Thanks for your help.
