### ISSUE TITLE
Why did you change the data set again?

### ISSUE THREAD

**Issue by ZhichaoOuyang** [xing-hu/EMSE-DeepCom#5]
I just processed the data set last week. Today, your data set on Google Drive is different.

**Comment by xing-hu** [comment]
I updated the data and outputs by different RQs. I think it would be more convenient for comparison.

**Comment by ZhichaoOuyang** [comment]
> I updated the data and outputs by different RQs. I think it would be more convenient for comparison.

Thank you for your answer, and by the way, can the previous dataset be used?
I see that although the size of the data set has not changed, the content of the data set is different. I have further processed your data set and it would be cumbersome to reprocess. Also, train.token.ast in your current training set is one line less than train.token.code

**Comment by xing-hu** [comment]
The difference between the two version dataset is the index of samples. In theory, it wouldn't affect the performance of your model. If you want to compare directly, I recommend this version as I provided the output of my model in the folder "output". 
Thanks for pointing the issue in train.token.ast, I will check it.

**Comment by ZhichaoOuyang** [comment]
I compared the old and new data sets, and found that some samples of the new data set are not on the old data set. Shouldn't you just disrupt the order, should you change some data samples? If so, I may still need to update the dataset for comparison.

**Comment by xing-hu** [comment]
Some samples may change when shuffled from the large codebase. 
I update the train.token.ast and hope the new one is more convenient for comparison.

**Comment by xing-hu** [comment]
I also reopen the old version dataset and the output on it. I hope both datasets can help your research.

**Comment by 9ayhub** [comment]
@ZhichaoOuyang

Hello, I have been able to run this code successfully using the data set given by the author，but the complete data processing code does not seem to be given, because I can't use the existing data processing code to generate the files provided by the author.

Can you successfully preprocess the data?If you can run it successfully, could you share me your code?
