### ISSUE TITLE
Could you provide the source code for SBT data generated by AST

### ISSUE THREAD

**Issue by ZhichaoOuyang** [xing-hu/EMSE-DeepCom#8]
Thank you very much！

**Comment by codekali** [comment]
I need the code for SBT too. It's really urgent.

**Comment by ZhichaoOuyang** [comment]
> I need the code for SBT too. It's really urgent.

I have finished writing this code for SBT

**Comment by codekali** [comment]
@ZhichaoOuyang Can you please share it to me?

**Comment by codekali** [comment]
> 
> 
> > I need the code for SBT too. It's really urgent.
> 
> I have finished writing this code for SBT

Please share a link to the code or repository. I'm stuck in the middle.

**Comment by 9ayhub** [comment]
> Thank you very much！

Can you run this program successfully? Are there any other missing files?

**Comment by 9ayhub** [comment]
@ZhichaoOuyang Can you run this program successfully? Are there any other missing files?

**Comment by codekali** [comment]
@9ayhub  I tried it running some months back but due to the lack of ```generateSBT``` file I could not load the data. You can probably run this project now after downloading the ```version 1``` data mentioned in the readme.

**Comment by 9ayhub** [comment]
@ZhichaoOuyang Hi, do you know the function of these three documents? How can I generate them?

```
vocab.nl
vocab.code
vocab.sbt
```

**Comment by 9ayhub** [comment]
@codekali Hi, do you know the function of these three documents? How can I generate them?

```
vocab.nl
vocab.code
vocab.sbt
```

**Comment by codekali** [comment]
@9ayhub These documents are as follows:
```
vocab.nl :  This is the vocabulary file containing every word required for generating and decoding summaries.
vocab.code :  This is the vocabulary file containing every java token which is used to build a java function or java program.
vocab.sbt : This is the vocabulary file containing every word which can be present in the structure based traversal of the abstract syntax tree of java methods.
```
